<a href="https://colab.research.google.com/github/rostovcevartem209/Pandas/blob/main/Pandas_teach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

countries = pd.Series(
    data = ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ'],
    name = 'Страны'
)
countries

#создание при помощи словаря
countries = pd.Series({
    'UK': 'Англия',
    'CA': 'Канада',
    'US': 'США',
    'RU': 'Россия',
    'BY': 'Беларусь',
    'KZ': 'Казахстан'},
    name = 'countries'
)
countries.loc[['UK', 'US', 'CA']] #доступ по ключам
countries.iloc[[1,4]] #доступ по порядковым номерам

CA      Канада
BY    Беларусь
Name: countries, dtype: object

DATAFRAME

In [ ]:
#задаем словарем, где ключи - название столбцов, списки - строки
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24,  9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 207600, 2724902]
})

countries_df.index = ['UK', 'CA', 'US', 'RU', 'BY', 'KZ'] #задаем индексы
countries_df

#создание из вложенного списка
countries_df = pd.DataFrame(
        data = [
        ['Англия', 56.29, 133396],
        ['Канада', 38.05, 9984670],
        ['США', 322.28, 9826630],
        ['Россия', 146.24, 17125191],
        ['Беларусь', 9.5, 207600],
        ['Казахстан', 17.04, 2724902]
    ],
        columns = ['COUNTRIES', 'POPULATION', 'AREA'],
        index = ['UK', 'CA', 'US', 'RU', 'BY', 'KZ'],
)
# Среднее по каждому столбцу (axis=0)
countries_df.mean(axis=0, numeric_only=True) #numeric_only - означает что вычесления производятся только для числовых значений

countries_df.POPULATION #доступ к столбцу по названию
countries_df['AREA']

#доступ к конкретным ячейкам
countries_df.loc['UK', 'AREA']
countries_df.loc['RU', ['POPULATION', 'AREA']]
countries_df.loc[['BY', 'KZ'], ['POPULATION', 'AREA']]
countries_df.iloc[2:7,1:3]

    POPULATION      AREA
US      322.28   9826630
RU      146.24  17125191
BY        9.50    207600
KZ       17.04   2724902

РАБОТА С ФАЙЛАМИ

In [10]:
# !mkdir data
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],  # население в млн
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]  # площадь в км²
})
countries_df.to_csv('data/countries.csv', index=False, sep=';') #загрузка в папку дата csv файла

countries_data = pd.read_csv('/content/data/countries.csv', sep = ';') #выгрузка из папки data csv файла
countries_data

data = pd.read_csv('https://raw.githubusercontent.com/esabunor/MLWorkspace/master/melb_data.csv') #загрузка файла по ссылке из интернета
data.head()  # выводим первые строки для проверки

# Сохранение в Excel
countries_df.to_excel('data/countries.xlsx', index=False)

# Чтение из Excel
excel_data = pd.read_excel('data/countries.xlsx')

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2        США      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5   Беларусь        9.50    207600
6  Казахстан       17.04   2724902

РЕАЛЬНЫЙ ДАТАСЕТ

In [51]:
# Загрузка данных по ссылке
melb_data = pd.read_csv('https://raw.githubusercontent.com/esabunor/MLWorkspace/master/melb_data.csv')

mask = melb_data['Price']>2000000
melb_data[mask].head()

#найдем количество трехкомнатных квартир
melb_data[melb_data['Rooms']==3].shape[0]

#найдем трехкомнатные кватриры дешевле 300 тыс.
melb_data[(melb_data['Rooms']==3) & (melb_data['Price']<300000)].shape[0]

#объекты дешевле 300 тысяч, у которых либо 3 комнаты, либо площадь больше 100 м²
melb_data[(melb_data['Price']<300000) & ((melb_data['Rooms']==3)|(melb_data['BuildingArea']>100))].shape[0]

#Максимальное количество комнат в таунхаусах
melb_data[melb_data['Type']=='t']['Rooms'].max()

#Медианная площадь объектов дороже среднего
mean_price = melb_data['Price'].mean()
melb_data[melb_data['Price']>mean_price]['BuildingArea'].median()

melb_data[melb_data['Bathroom']==0].shape[0]
melb_data[(melb_data['SellerG']=='Nelson')&(melb_data['Price']>3000000)].shape[0]
melb_data[melb_data['BuildingArea']==0]['Price'].min()

#Какова средняя цена объектов недвижимости в таблице melb_data с ценой менее одного миллиона, в которых либо количество комнат больше пяти, либо здание моложе 2015 года?
melb_data[(melb_data['Price']<1000000)&((melb_data['Rooms']>5)|(melb_data['YearBuilt']>2015))]['Price'].mean()

#В каком районе Мельбурна чаще всего продаются виллы и коттеджи (тип здания — h) с ценой меньше трёх миллионов?
#ПРИ ПОМОЩИ СЛОВАРЯ
lst = list(melb_data[(melb_data['Type']=='h')&(melb_data['Price']<3000000)]['Regionname'])
dict = {}
for i in set(lst):
  dict[lst.count(i)] = i
print(max(dict))

#БЕЗ СЛОВАРЯ
melb_data[(melb_data['Type']=='h')&(melb_data['Price']<3000000)]['Regionname'].value_counts()[0]

3451

/tmp/ipykernel_11355/2388661138.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  melb_data[(melb_data['Type']=='h')&(melb_data['Price']<3000000)]['Regionname'].value_counts()[0]

np.int64(3451)